import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/UI/header";
import Footer from "@/components/UI/footer";
import { Work_Sans } from "next/font/google";
import Toolbar from "@/components/toolbar/toolbar";

const workSans = Work_Sans({
	subsets: ["latin"],
	display: "swap",
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={workSans.className}>
				<Header />
				{children}
				{/* <Toolbar/> */}
				<Footer />
			</body>
		</html>
	);
}
