import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/UI/header";
import Footer from "@/components/UI/footer";
import { Work_Sans } from "next/font/google";
import SideBar from "@/components/sideBar/sideBar";
import { ClerkProvider } from "@clerk/nextjs";

const workSans = Work_Sans({
	subsets: ["latin"],
	display: "swap",
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ClerkProvider>
				<body className={workSans.className}>
					<Header />
					{children}
					{/* <SideBar/> */}
					<Footer />
				</body>
			</ClerkProvider>
		</html>
	);
}
